source "https://rubygems.org"

ruby "2.1.2"
gem "unicorn"
gem "sinatra"
gem "sinatra-support", require: "sinatra/support"
gem "sinatra-assetpack", :require => "sinatra/assetpack"

gem "coffee-script"
gem "compass"
gem "compass-h5bp"
gem "mustache"
