source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-assetpack"
gem "sinatra-static-assets"
gem "sinatra-flash"
gem "datamapper"
gem "dm-migrations"
gem "rack"
gem "tesseract-ocr"

group :development do 
	gem "dm-sqlite-adapter"
end
